// Generated by protoc-gen-ts
export interface User {
	id: string;
	name: string;
	email: string;
}

export const UserCodec = {
	encode: (user: User) => JSON.stringify(user),
	decode: (data: string) => JSON.parse(data) as User,
};
