import fs from "node:fs/promises";
import packageJson from "../package.json" assert { type: "json" };

const { name, version } = packageJson;

const template = `
// This file is generated by scripts/code-gen-meta.ts. Do not modify this file directly.

export const packageName = "${name}";

export const packageVersion = "${version}";
`.trimStart();

async function main() {
	await fs.writeFile("src/meta.ts", template, "utf8");
}

void (await main());
